// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6boDU-TwHlCFhz3FTxGmIsNeqHheN6NM',
    appId: '1:197559914847:web:897b595994a292b94d26ea',
    messagingSenderId: '197559914847',
    projectId: 'cms-end-ac06e',
    authDomain: 'cms-end-ac06e.firebaseapp.com',
    storageBucket: 'cms-end-ac06e.firebasestorage.app',
    measurementId: 'G-2GQEB0WDH3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCLwy-i6CpfSikEB1T_UE0jUhLCOzTUoY',
    appId: '1:197559914847:android:634b17248de1a1724d26ea',
    messagingSenderId: '197559914847',
    projectId: 'cms-end-ac06e',
    storageBucket: 'cms-end-ac06e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtlnEPkxz_Q5vxXz3AtpZVDtG4eyWqQZg',
    appId: '1:197559914847:ios:8bfe71a3d1f4f50f4d26ea',
    messagingSenderId: '197559914847',
    projectId: 'cms-end-ac06e',
    storageBucket: 'cms-end-ac06e.firebasestorage.app',
    iosBundleId: 'com.example.cms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtlnEPkxz_Q5vxXz3AtpZVDtG4eyWqQZg',
    appId: '1:197559914847:ios:8bfe71a3d1f4f50f4d26ea',
    messagingSenderId: '197559914847',
    projectId: 'cms-end-ac06e',
    storageBucket: 'cms-end-ac06e.firebasestorage.app',
    iosBundleId: 'com.example.cms',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6boDU-TwHlCFhz3FTxGmIsNeqHheN6NM',
    appId: '1:197559914847:web:ee6fa6ca9a85834c4d26ea',
    messagingSenderId: '197559914847',
    projectId: 'cms-end-ac06e',
    authDomain: 'cms-end-ac06e.firebaseapp.com',
    storageBucket: 'cms-end-ac06e.firebasestorage.app',
    measurementId: 'G-XMC65Y9XKQ',
  );
}
